Enquete/Enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('enquete/', include('main.urls')),
    path('diario/', include('diario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

Enquete/diario/urls.py
from django.urls import path
from . import views

app_name = 'diario'
urlpatterns = [
    path('',
        views.IndexView.as_view(), name='index'
    ),
    path('<int:pk>',
        views.DiarioView.as_view(), name='diario'
    ),
    path('entrada/<int:pk>',
        views.EntradaView.as_view(), name='entrada'
    ),
    path('perfio/<int:pk>',
        views.PerfioView.as_view(), name='perfio'
    ),
]

Enquete/home/urls.py
from django. urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

Enquete/main/urls.py
from django. urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('',
        views.IndexView.as_view(), name='index'
    ),
    path('<int:pk>', views.DetalhesView.as_view(), name='detalhes'
    ),
    path('<int:pk>/resultado', views.ResultadoView.as_view(), name='resultado'
    ),
    path('<int:id_enquete>/voltacao', views.votacao, name='votacao'
    ),
    path('classificacao/<int:pk>', views.ClassificacaoView.as_view(), name='classificacao'
    ),
]

Enquete/diario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Usuario(models.Model):
    user = models.OneToOneField(
        User, on_delete = models.CASCADE,
        null=True,
        default=None,
        verbose_name = 'Usuário',
    )
    nick = models.CharField(
        'Apelido',
        max_length = 20,
    )
    biografia = models.TextField(
        max_length = 2000
    )
    data_nascimento = models.DateField(
        'Data de nascimento', null=True, default=None
    )
    def __str__(self):
        return self.nick

    #usuario tem login e senha e um diario
class Diario(models.Model):
    #diario tem entradas
    #tem que ter chave pra usuario e entradas
    nome_diario = models.CharField(
        'Nome do Diario',
        max_length = 20,
        blank = True
    )
    dono = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, default=None
    )
    def __str__(self):
        return self.nome_diario
    def todos_os_diarios(self):
        return self.nome_diario


class Entrada(models.Model):
    diario = models.ForeignKey(
        Diario, on_delete=models.CASCADE, null=True, default=None
    )

    data = models.DateTimeField(
        auto_now_add = True
    )
    titulo = models.CharField(
        'Título da Entrada',
        max_length = 120,
        blank = True,
        null = True,
    )
    texto = models.TextField(
        max_length = 5000
    )
    imagem = models.ImageField(
        upload_to = 'entrada/media',
        null=True, default=None,
    )
    def __str__(self):
        return self.titulo

Enquete/home/models.py
from django.db import models

# Create your models here.

Enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Classificacao(models.Model):
    titulo = models.CharField(max_length=30)
    descricao = models.CharField(max_length=200)
    data_criacao = models.DateTimeField('Data de criação')
    def __str__(self):
        return self.titulo

#classe pergunta(que erda de models.Model)
class Pergunta(models.Model):
    texto = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('Data de publicação')
    classificacao = models.ForeignKey(Classificacao, on_delete=models.CASCADE, null=True, default=None )
    def __str__(self):
        #padrão receber self
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora
        #    (passado)                          (tempo da pergunta)  (não no futuro)

    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'Últimas 24h?'

class Opcao(models.Model):
    # Qual a naturesa desse models.XXXXXX? é um tipo? é uma erança?
    texto = models.CharField(max_length = 200)
    votos = models.IntegerField(default = 0)
    #fazendo ligação entre 2 classes e o banco (mapear relacionamento):
    pergunta = models.ForeignKey(Pergunta,on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

Enquete/diario/views.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Usuario, Diario, Entrada
##from django.contrib.auth.forms import authenticate, login, logout


# Create your views here.
# por enquanto exibe os usuarios
@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'diario/index.html'
    model = Diario
    context_object_name = 'os_diarios'

#Exibir o que tem dentro do diario(as entradas)
@method_decorator(login_required, name='dispatch')
class DiarioView(generic.DetailView):
    template_name = 'diario/diario.html'
    model = Diario

#Exibir a entrada
@method_decorator(login_required, name='dispatch')
class EntradaView(generic.DetailView):
    template_name = 'diario/entrada.html'
    model = Entrada

@method_decorator(login_required, name='dispatch')
class PerfioView(generic.DetailView):
    template_name = 'diario/perfio.html'
    model = Usuario

Enquete/home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html', {})

Enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Pergunta, Opcao, Classificacao

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'ultimas_perguntas' #de onde vem essa variavel de contexto?
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now()). order_by('-data_publicacao')[:10]

class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'main/detalhes.html'
    #vou sobrescrever o metodo por causa do problema de alcaçar perguntas no futuro
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())

class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'

def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request,'main/detalhes.html',{
            'pergunta': pergunta,
            'error_mensage':"Selecione uma opção VÁLIDA!"
        })
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(
            reverse('main:resultado', args=(pergunta.id,))
        )

class ClassificacaoView(generic.DetailView):
    model = Classificacao


    '''
    context_object_name = 'perguntas_classificacao'
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now()). order_by('texto')

    '''

Enquete/diario/templates/diario/diario.html
<html>
    <head>
        <title>Meu Diario :)</title>
    <!-- aqui eu listo as entradas -->
    </head>
    <body>
        {% if diario %}
            <h1>Diario: {{diario.nome_diario}}</h1>
            <a href="{% url 'diario:perfio' diario.dono.usuario.id %}">
                {{ diario.dono.usuario.nick }}
            </a>
            <ul>
                {% for entrada in diario.entrada_set.all %}
                    <li>
                        <a href="{% url 'diario:entrada' entrada.id %}">
                            {{entrada.titulo}}
                        </a>
                    </li>
                {% endfor %}
            </ul>

        {% else %}
            <p>não há entradas cadastradas</p>
        {% endif %}

    </body>
</html>

<!--
<html>
    <head>
        <title>Meu Diario :)</title>

    </head>
    <body>
        {% if diario %}
            <h1>Diario: {{diario.nome_diario}}</h1>
            <ul>
                {% for entrada in diario.entrada_set.all %}
                    <li>
                        <a href="{% url 'diario:entrada' entrada.id %}">
                            {{ entrada.titulo}}
                        </a>
                    </li>
                {% endfor %}
            </ul>

        {% else %}
            <p>não há entradas cadastradas</p>
        {% endif %}

    </body>
</html>
-->

Enquete/diario/templates/diario/entrada.html
<html>
    <!-- aqui eu detalho as entradas -->
    <head>
        <title>{{entrada.titulo}}</title>
    </head>
    <body>
        {% if entrada %}
            <h1>Entrada: {{entrada.titulo}}</h1></br></br>

            <p>
                {{entrada.texto}}
            </p>

        <!-- depois insira a imagem -->
        <figure>
            <img src= {{ entrada.imagem.url }} >
        </figure>

        {% else %}
            <p>entrada bugada</p>
        {% endif %}

    </body>
</html>

Enquete/diario/templates/diario/index.html
<html>
    <head>
        <title>Meu Diario</title>
    <!-- aqui eu listo os diarios -->
    </head>
    <body>
        {% if os_diarios %}
            <h1>Lista dos diarios</h1>
            <ul>
                 {% for diario in os_diarios %}
                    <li>
                        <a href="{% url 'diario:diario' diario.id %}">
                            {{ diario.nome_diario }}
                        </a>
                    </li>
                {% endfor %}
            </ul>


        {% else %}
            <p>não há diarios cadastrados</p>
        {% endif %}

    </body>
</html>

<!---
<html>
    <head>
        <title>Meu Diario</title>

    </head>
    <body>
        {% if os_diarios %}
            <h1>Lista dos diarios</h1>
            <ul>
                {% for diario in os_diarios %}
                    <li>
                        <a href="{% url 'diario:diario' diario.id %}">
                            {{ diario.nome_diario }}
                        </a>
                    </li>
                {% endfor %}
            </ul>


        {% else %}
            <p>não há diarios cadastrados</p>
        {% endif %}

    </body>

</html>
--->

Enquete/diario/templates/diario/perfio.html
<html>
    <head>
        <title> Meu Perfio :) </title>
    </head>
    <body>
        <h1> Perfio </h1> </br>
        <p>Nick Name: {{usuario.nick}}</p> </br>
        <p>Data de Nasciemnto:{{ usuario.data_nascimento }} </p> </br>
        <p>Biografia: </br>{{ usuario.biografia }} </p>

    </body>
</html>

Enquete/home/templates/home/index.html
<html>
    <head>
        <title> Home </title>
    <head>
    <body>
        <h1>Bem vindo a home</h1>
        <a href="{% url 'main:index' %}"> Aplicação enquete </a></br>
        <a href="{% url 'diario:index' %}"> Aplicação Diario </a>
    </body>
</html>

Enquete/main/templates/main/classificacao_detail.html
<html>
    <head>
        <title> Classificação  </title>
    </head>
    <body>
        <h1>Perguntas da classificação: {{classficacao.id}}</h1>
        <u>Classificacao:</u> {{classificacao.titulo}}</br>
        <u>Descricao</u>{{classificacao.descricao}}</br>
        <u>Data de Publicação</u>: {{classificacao.data_criacao}}

        <ol>
            {% for pergunta in classificacao.pergunta_set.all %}
                <li>
                    <a href="{% url 'main:detalhes' pergunta.id %}">
                        {{ pergunta.texto }}
                    </a>
                </li>
            {% endfor %}

        </ol>


    </body>
</html>

Enquete/main/templates/main/detalhes.html
<html>
    <head>
        <title> App Enquete </title>
    </head>
    <body>
        <h1>Detalhes da Enquete {{pergunta.id}}</h1>

        <u>Pergunta</u>: {{ pergunta.texto }}</br>
        <u>Data de Publicação</u>: {{ pergunta.data_publicacao }}</br>
        <u>Classificação:</u> <a href="{% url 'main:classificacao' pergunta.classificacao.id %}"> {{ pergunta.classificacao.titulo }} </a>
        {% if error_mensage %}
            <hr>
            <strong>{{ error_message }}</strong>
        {% endif %}
        <form action="{% url 'main:votacao' pergunta.id %}" method="post">
            {% csrf_token %}

            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li>
                        <input type="radio" name="opcao"
                        id="opcao{{ forloop.counter }}" value = "{{ opcao.id }}" >
                        <label for="opcao{{ forloop.counter }}">
                            {{ opcao.texto }}
                        </label>
                    </li>
                {% endfor %}
            </ul>
            <input type="submit" value="Registre o seu voto">
        </form>


    </body>
</html>

Enquete/main/templates/main/index.html
{% load static %}
<html>
    <head>
        <title> App Enquete </title>
        <link rel="stylesheet" type"text/css" href="{% static 'main/style.css' %}">
    <head>
    <body>
        {% if ultimas_perguntas %}
            <h1>Listas das Últimas enquetes</h1>
            <ul>
                {% for pergunta in ultimas_perguntas %}
                    <li>
                        <a href="{% url 'main:detalhes' pergunta.id %}">
                             {{ pergunta.texto }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Não há enquetes cadastradas até o momento!</p>
        {% endif %}


    </body>

</html>

Enquete/main/templates/main/resultado.html
<html>
    <head>
        <title>App Enquete</title>
    </head>
    <body>
        <h2>Resultado Parcial da Enquete {{ pergunta.id }} </h2>
        <u>Pergunta</u>: {{pergunta.texto}}</br>
        <u>Data de Publicação</u>: {{pergunta.data_publicacao}}
        <ul>
            {% for opcao in pergunta.opcao_set.all %}
                    <li>{{ opcao.texto }} = {{ opcao.votos }}
                    voto{{ opcao.votos | pluralize }}</li>
            {% endfor %}
        </ul>
        <hr/>
        <a href="{% url 'main:detalhes' pergunta.id %}">Deseja votar novamente?</a> |
        <a href="{% url 'main:index' %}"> Retornar à página principal </a>
    </body>
</html>